"""
MAM session cookie management.

The `mam_id` cookie is the ONLY auth mechanism MAM exposes — every
HTTP call (.torrent grab, dynamic-seedbox ping, search probe) is
authenticated by attaching that cookie as an HTTP header. The cookie
is generated by the user via Preferences → Security on the MAM site,
locked to either an IP or an ASN, and (in practice) needs to be
rotated about once a month.

This module is a slimmed-down lift from
`athena-scout/app/sources/mam.py`. AthenaScout uses MAM for book
search; Hermeece uses MAM for IRC announces and .torrent file fetches.
The shared surface is the auth layer — the HTTP client, the IP register
flow, the cookie validation probe — and that's what this file contains.

Two non-obvious choices, both load-bearing — do NOT change without a
real-world end-to-end check first:

  1. The `curl/8.0` User-Agent is intentional. It's the UA that has
     been verified to work against MAM end-to-end in AthenaScout.
     MAM has bitten us with subtle UA-based rejection before.
  2. `http2=False` is explicit. httpx can speak HTTP/2 when the `h2`
     package is installed; we pin HTTP/1.1 because that's what's been
     verified against MAM and we don't want variable transport
     behavior creeping in.

The validation probe deliberately uses MAM's search endpoint (a tiny
JSON POST) rather than scraping HTML. The endpoint is stable, returns
clear status codes, and is the exact path AthenaScout already battle-
tests on every scan, so we know it works.
"""
from __future__ import annotations

import asyncio
import json
import logging
from typing import Optional

import httpx

_log = logging.getLogger("hermeece.mam.cookie")


# ─── MAM endpoint constants ──────────────────────────────────

MAM_BASE_URL = "https://www.myanonamouse.net/"
MAM_SEARCH_URL = "https://www.myanonamouse.net/tor/js/loadSearchJSONbasic.php"
MAM_DYNIP_URL = "https://t.myanonamouse.net/json/dynamicSeedbox.php"

# Numeric category id for "Ebooks" — used by the validation probe to
# constrain the test search payload. The exact value doesn't matter
# much (we don't read any of the results), but we need a valid category
# or MAM may reject the payload.
_EBOOK_CATEGORY = "14"
_ENGLISH_LANG_ID = 1

# Tiny JSON payload sent to the search endpoint to verify auth. We
# don't care about the response body — we only need to know whether
# the request was accepted (cookie valid) or rejected (cookie invalid
# / IP mismatch / ASN mismatch). Pre-serialized so the body bytes go
# on the wire untouched (see _do_post for why).
_AUTH_PROBE_PAYLOAD = json.dumps(
    {
        "tor": {
            "text": "test",
            "srchIn": {"title": "true"},
            "searchType": "active",
            "searchIn": "torrents",
            "main_cat": [_EBOOK_CATEGORY],
            "browse_lang": [_ENGLISH_LANG_ID],
            "startNumber": "0",
        },
        "perpage": 5,
    }
)


# ─── HTTP layer ──────────────────────────────────────────────

_client: Optional[httpx.AsyncClient] = None


def build_headers(token: str) -> dict[str, str]:
    """Build the standard MAM request headers for a given session token.

    Public so the grab path (`mam.grab`) can reuse the exact same
    header set when fetching .torrent files. Keeping the construction
    in one place means a UA change or a header tweak is a single edit.
    """
    return {
        "Content-Type": "application/json",
        "User-Agent": "curl/8.0",
        "Cookie": f"mam_id={token}",
    }


def get_client() -> httpx.AsyncClient:
    """Lazy-initialized module-level httpx.AsyncClient for connection reuse.

    MUST be called from within a running asyncio event loop — the
    client binds to whichever loop is active at creation time.
    Hermeece runs one uvicorn loop for the whole process lifetime, so
    this is safe.
    """
    global _client
    if _client is None:
        _client = httpx.AsyncClient(
            http2=False,
            timeout=httpx.Timeout(20.0, connect=10.0),
            follow_redirects=True,
        )
        _log.debug("MAM httpx.AsyncClient created")
    return _client


async def aclose_session() -> None:
    """Tear down the module-level AsyncClient.

    Called from `main.py`'s lifespan during app shutdown. Safe to call
    multiple times — subsequent calls are no-ops. The `a` prefix is
    deliberate: callers must `await` to actually close the underlying
    transport.
    """
    global _client
    if _client is not None:
        try:
            await _client.aclose()
            _log.debug("MAM httpx.AsyncClient closed")
        except Exception as e:
            _log.warning(f"Error closing MAM client: {e}")
        finally:
            _client = None


async def _do_get(url: str, token: str, timeout: int = 15) -> httpx.Response:
    """Async GET to a MAM endpoint with the standard auth header set."""
    return await get_client().get(
        url, headers=build_headers(token), timeout=timeout
    )


async def _do_post(
    url: str, token: str, payload: str, timeout: int = 20
) -> httpx.Response:
    """Async POST to a MAM endpoint with the standard auth header set.

    `payload` MUST be a pre-serialized JSON string. Sent via httpx's
    `content=` parameter so the body bytes go on the wire untouched.
    `data=<dict>` (form-url-encoded) and `json=<dict>` (re-serialized
    by httpx) both break the MAM search API in subtle ways: MAM
    happily accepts the request and returns HTTP 200 with a zero-byte
    body, which looks exactly like an auth failure but isn't. The fix
    (verified the hard way in AthenaScout) is sending exact JSON bytes.
    """
    return await get_client().post(
        url, headers=build_headers(token), content=payload, timeout=timeout
    )


# ─── Validation flow ─────────────────────────────────────────


async def register_ip(token: str, skip_ip_update: bool = True) -> dict:
    """Ping MAM's dynamic-seedbox endpoint to register the server's IP.

    Most users (Hermeece included by default) lock their session to an
    ASN rather than a single IP, in which case this call is unnecessary
    and the function short-circuits to success without hitting MAM.
    The `skip_ip_update=True` default reflects the safer common case;
    set it to False on a per-call basis if you know your session is
    IP-locked rather than ASN-locked.

    Returns: `{"success": bool, "message": str, ...optional fields}`.
    Never raises — failures come back as `success=False` with a
    human-readable message ready for the UI.
    """
    if skip_ip_update:
        return {
            "success": True,
            "message": "Skipped IP registration (ASN-locked session)",
        }

    _log.info("Registering server IP with MAM...")

    try:
        resp = await _do_get(MAM_DYNIP_URL, token)
        body = resp.text.strip()
        _log.debug(f"IP registration response: {body}")

        # MAM dynamicSeedbox.php returns JSON like:
        #   {"Success": true, "msg": "Completed", "ip": "...",
        #    "ASN": 12345, "AS": "..."}
        # On failure msg may be "No Session Cookie", "Invalid session -
        # IP mismatch", "Last Change too recent", etc.
        try:
            data = resp.json()
        except Exception:
            if "<html" in body.lower():
                return {
                    "success": False,
                    "message": "Got HTML login page — token wrong or expired",
                }
            return {
                "success": False,
                "message": f"Non-JSON response: {body[:200]}",
            }

        msg = str(data.get("msg", "")).strip()
        if data.get("Success"):
            _log.info(f"IP registration OK ({msg or 'no message'})")
            return {
                "success": True,
                "message": msg or "OK",
                "ip": data.get("ip"),
                "asn": data.get("ASN"),
                "as_org": data.get("AS"),
            }

        # Success=false branch — translate known msg values to clear
        # human-readable messages for the UI.
        msg_l = msg.lower()
        if "incorrect session type" in msg_l:
            _log.warning("ASN-locked session — IP registration not needed")
            return {
                "success": True,
                "message": "ASN-locked session — IP registration not needed",
            }
        if "no session cookie" in msg_l or "invalid cookie" in msg_l:
            return {
                "success": False,
                "message": "Token not recognized by MAM",
            }
        if "ip mismatch" in msg_l or "asn mismatch" in msg_l:
            return {
                "success": False,
                "message": f"Session locked to a different network: {msg}",
            }
        if "too recent" in msg_l:
            return {
                "success": False,
                "message": f"IP change rate-limited by MAM: {msg}",
            }
        return {
            "success": False,
            "message": msg or f"Unexpected response: {body[:200]}",
        }
    except asyncio.TimeoutError:
        return {"success": False, "message": "Timeout connecting to MAM"}
    except Exception:
        # Log the full traceback server-side but return a generic
        # message: exception details can leak library versions,
        # internal hostnames, or stack frame paths through API
        # response bodies.
        _log.exception("MAM IP-registration network error")
        return {
            "success": False,
            "message": "Network error connecting to MAM dynamic seedbox endpoint",
        }


async def verify_session(token: str) -> dict:
    """Probe the MAM search endpoint to verify the cookie is accepted.

    Returns: `{"success": bool, "message": str}`.

    The probe payload is a tiny English ebook search — we don't read
    the results, we only care whether MAM accepted the request. A
    HTTP 200 with a non-empty body means the cookie is valid; HTTP 200
    with a zero-byte body or HTTP 403 means the cookie is rejected.

    The session-validation strategy is identical to AthenaScout's
    `verify_search_auth` — kept the same way deliberately so both
    apps share their understanding of "what does a working cookie
    look like" and a MAM-side change that breaks one app would
    fail-fast in the other too.
    """
    _log.info("Verifying MAM session cookie...")

    try:
        resp = await _do_post(MAM_SEARCH_URL, token, _AUTH_PROBE_PAYLOAD, 15)
        if resp.status_code == 200 and len(resp.text) > 0:
            _log.info("MAM session cookie OK")
            return {"success": True, "message": "Connection successful"}
        if resp.status_code == 200 and len(resp.text) == 0:
            return {
                "success": False,
                "message": "HTTP 200 but empty response — token may be invalid or expired",
            }
        if resp.status_code == 403:
            return {
                "success": False,
                "message": "HTTP 403 — session rejected. Check token validity for this server's IP/ASN.",
            }
        return {
            "success": False,
            "message": f"Unexpected HTTP {resp.status_code}",
        }
    except Exception:
        _log.exception("MAM session-verify network error")
        return {
            "success": False,
            "message": "Network error verifying MAM session",
        }


async def validate(token: str, skip_ip_update: bool = True) -> dict:
    """Full validation: IP registration (if applicable) + session probe.

    Composite of `register_ip` and `verify_session`. Used by the
    background cookie-check job and by the Settings UI's "test cookie"
    button. Returns the same shape as `verify_session` plus the
    sub-results so the UI can show which step failed.
    """
    if not token:
        return {
            "success": False,
            "message": "No MAM session cookie configured",
            "ip_result": None,
            "search_result": None,
        }

    ip_result = await register_ip(token, skip_ip_update)
    if not ip_result["success"]:
        return {
            "success": False,
            "message": f"IP registration failed: {ip_result['message']}",
            "ip_result": ip_result,
            "search_result": None,
        }

    search_result = await verify_session(token)
    return {
        "success": search_result["success"],
        "message": (
            search_result["message"]
            if search_result["success"]
            else f"Session verify failed: {search_result['message']}"
        ),
        "ip_result": ip_result,
        "search_result": search_result,
    }
